### ISSUE TITLE
Bold and Italic variants need correct style/subfamily metadata

### ISSUE THREAD

**Issue by christopheradams** [impallari/Libre-Caslon-Text#3]
I've noticed that the font files for the Bold and Italic variants have the style/subfamily field incorrectly set to "Regular", instead of "Bold" and "Italic", respectively.

**Comment by christopheradams** [comment]
Similarly, the style and weight are set to "normal".

**Comment by synthview** [comment]
Hi, yes the style naming seems wrong. Could you provide UFO if you don’t plan to fix the font on your side please?

**Comment by impallari** [comment]
Ups, sorry about that! Will update soon.
Thanks for reporting the issue

**Comment by impallari** [comment]
Fixed
